### ISSUE TITLE
[❗️Error Handling] [Xcode] react-native-vector-icons 설치 시 Xcode 빌드 failed

### ISSUE THREAD

**Issue by fz7948** [FoodRriend/FoodRiend-client#27]
### 어떤 에러인가요?

같은 파일명이 중복되어서 발생하는 에러인데 Xcode에서 빌드시 에러가 발생

### 에러 메시지

```
Multiple commands produce Error/...파일명/
```

### 에러 핸들링 방법

제일 마지막에 보여지는 파일명이 중복되어서 나타나는 에러인걸 인터넷 검색을 통해 알아내고 Xcode안에서 파일을 지워보고 다시 빌드해도 해결이 되지않았다. VScode에서 어떤 부분이 중복이 되는지 찾아봤고 `project.pbxproj`라는 파일에 `Info.plist`와 `Ionicons.ttf`가 각각 중복되어있었고 이 코드들을 지워주니 빌드가 성공적으로 완료되었다.

Xcode에 임의로 파일을 생성하거나 추가하면 VScode `project.pbxproj`파일에 자동으로 추가가 된다. 빌드시엔 `Info.plist`파일에 자동으로 해당 파일이 추가가 되어지는데 `project.pbxproj`파일과 `Info.plist`파일에 중복이 발생하면서 에러가 발생하는거 같은데 왜 이렇게 되는건지 모르겠다. 나의 경우 파일의 코드를 지웠는데 이게 맞는 해결법인지도 잘 모르겠다. 우선 빌드는 성공적으로 되고 아이콘도 성공적으로 불러와지니 해결되었다고 봐야되는걸까...?

### 에러 핸들링을 위해 참고한 레퍼런스 링크

https://github.com/oblador/react-native-vector-icons
https://ozofweird.tistory.com/entry/React-Native-React-Native-Vector-Icons
https://zetal.tistory.com/entry/Multiple-commands-produce-Error-%ED%95%B4%EA%B2%B0%EB%B2%95

**Comment by jeongro123** [comment]
에고.. 초기 세팅하시고 에러 핸들링까지 하시느라 너무 고생 많으셨습니다 ㅠㅠ👍
